language: node_js
node_js:
- '10'
install:
- npm i
script:
- npm run build
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts:
    - 49.232.0.208 
before_install:
  - openssl aes-256-cbc -K $encrypted_efe2ee7fba5d_key -iv $encrypted_efe2ee7fba5d_iv
  -in tencentCloud.enc -out ~/.ssh/tencentCloud -d

after_success: #构建成功
