language: node_js
node_js:
- '10'
install:
- npm i
script:
- npm run build
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts:
  - 49.232.0.208
before_install:
- openssl aes-256-cbc -K $encrypted_efe2ee7fba5d_key -iv $encrypted_efe2ee7fba5d_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
after_success:
- chmod 600 ~/.ssh/id_rsa
- tar -czvf public.tar public/
- scp public.tar root@49.232.0.208:/
- ssh root@49.232.0.208
- cd /
- tar -xzvf public.tar
