language: node_js
node_js:
- '10'
install:
- npm i
script:
- npm run build
cache:
  directories:
  - node_modules
after_success: 
before_install:
- openssl aes-256-cbc -K $encrypted_efe2ee7fba5d_key -iv $encrypted_efe2ee7fba5d_iv
  -in tencentCloud.enc -out ~\/.ssh/tencentCloud -d
